name: Build and publish static files

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
      - name: Install dependencies
        working-directory: ./react-web
        run: npm ci
      - name: Build
        working-directory: ./react-web
        run: npm run build
      - name: Compress build
        working-directory: ./react-web
        run: tar -czf ./build.tar.gz ./build/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./react-web/build.tar.gz
